version: "2"
services:
  nodeserver:
    container_name: node_server
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    links:
      - python

  python:
    container_name: python_server
    image: "python"
    user: "root"
    working_dir: "/home/python/app"
    volumes:
      - ./bot:/home/python/app
#    command: "python3 main.py"

volumes:
  db_volume:
    external: true